### ISSUE TITLE
Build failed when executing with xcode-beta

### ISSUE THREAD

**Issue by OxygenLost** [Kyle-Ye/iPhoneMirroringInject#2]
> xcodebuild -scheme iPhoneMirroringInject -configuration Release -derivedDataPath output
Command line invocation:
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/xcodebuild -scheme iPhoneMirroringInject -configuration Release -derivedDataPath output

User defaults from command line:
    IDEDerivedDataPathOverride = /Users/zhibiliunian/code/iPhoneMirroringInject/output
    IDEPackageSupportUseBuiltinSCM = YES

--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64e, id:00008103-001E555E0EA2001E, name:My Mac }
{ platform:macOS, arch:x86_64, id:00008103-001E555E0EA2001E, name:My Mac }
{ platform:macOS, name:Any Mac }
Prepare packages

ComputeTargetDependencyGraph
note: Building targets in dependency order
note: Target dependency graph (1 target)
    Target 'iPhoneMirroringInject' in project 'iPhoneMirroringInject' (no dependencies)

GatherProvisioningInputs

CreateBuildDescription

/Users/zhibiliunian/code/iPhoneMirroringInject/iPhoneMirroringInject.xcodeproj: error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "VB7MJ8R223" with a private key was found. (in target 'iPhoneMirroringInject' from project 'iPhoneMirroringInject')
** BUILD FAILED **

The following build commands failed:
	Building project iPhoneMirroringInject with scheme iPhoneMirroringInject and configuration Release
(1 failure)

**Comment by Kyle-Ye** [comment]
Fixed in 9ae4ecfdf0428b41f192765807d53a4862816689
