### ISSUE TITLE
build fault

### ISSUE THREAD

**Issue by Beilusquit90** [Kyle-Ye/iPhoneMirroringInject#3]
Executable=/Users/leonidstarcenko/work/iPhoneMirroringInject/iPhone Mirroring.app/Contents/MacOS/iPhone Mirroring
./iPhone Mirroring.app/Contents/MacOS/iPhone Mirroring: replacing existing signature
build.sh: line 24:  5014 Killed: 9               DYLD_INSERT_LIBRARIES=$IMINJECT_PATH ./iPhone\ Mirroring.app/Contents/MacOS/iPhone\ Mirroring

xcode-beta 16
macbook air m2 (8gb)
macOS 15 Beta 1(24A5264n)
idk what wrong with that =(

**Comment by Beilusquit90** [comment]
my fault.
<img width="690" alt="image" src="https://github.com/Kyle-Ye/iPhoneMirroringInject/assets/9270255/0a0e66b8-30d6-4192-964f-31f2c70cf525">

but. i still cant run it...

**Comment by sheikheddy** [comment]
Same here, can't run it.

**Comment by Kyle-Ye** [comment]
Since new macOS beta has removed the constraint. Close the issue for now.
